### PR TITLE
Add try except

### PR DESCRIPTION
**Pull request by DjamikTea**
sometimes broken packages arrive

### CODE REVIEW

**Comment by 2bndy5** [comment]
Instead of compensating in the code, you should check your wiring or try lowering the SPI speed ([`spi_frequency` kwarg](https://circuitpython-nrf24l01.readthedocs.io/en/latest/core_api/basic_api.html#circuitpython_nrf24l01.rf24.RF24.__init__.spi_frequency) for the constructor). This is often not a problem with the data that gets transmitted because CRC prevent data corruption, rather this is often a problem with the SPI connections.
```py
nrf = RF24(SPI_BUS, CSN_PIN, CE_PIN, spi_frequency=4000000)
```

**Comment by 2bndy5** [comment]
I am curious what device, specifically the MCU board, is experiencing the "broken packages"? And, are you using very long wires?

**Comment by DjamikTea** [comment]
I found the problem. Arduino sent some packets at startup. I change library, lmao

**Comment by 2bndy5** [comment]
In the future, please open an Issue first before submitting a Pull Request - this could've saved you needless work.

**Pull request closed without merging**
